import type { Metadata } from "next";
import localFont from "next/font/local";
<<<<<<< HEAD
import ReactQueryProvider from "@/../utils/ReactQueryProvider";
=======
>>>>>>> origin/main
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
<<<<<<< HEAD
=======

>>>>>>> origin/main
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
<<<<<<< HEAD
    <html className="" lang="fa" dir="rtl">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased  px-10`}
=======
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
>>>>>>> origin/main
      >
        {children}
      </body>
    </html>
  );
}
