import Crad from "@/components/dashbord/Crad";
import Navbar from "@/components/dashbord/Navbar";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html className="" lang="fa" dir="rtl">
      <body>
        {children}
      </body>
    </html>
  );
}
